const OFFICIAL_LANDMARK_SOURCE = {
  kto100: "문체부·한국관광공사 2025~2026 한국관광 100선",
  tourJeonbuk: "투어전북 전북문화관광 관광지정보",
};

const OFFICIAL_LANDMARKS = [
  { name: "전주한옥마을", city: "전주", category: "역사·문화", sourceLevel: "kto100" },
  {
    name: "전주3.1운동발상지",
    city: "전주",
    category: "역사·문화",
    sourceLevel: "tourJeonbuk",
    qrCodeId: "jeonju-3-1-birthplace",
    qrImageFile: "전주3.1운동발상지.svg",
    qrPayload: "TANGAMJA:CHECKIN:JEONJU-3-1-MOVEMENT-BIRTHPLACE:v1",
  },
  { name: "내장산국립공원", city: "정읍", category: "자연", sourceLevel: "kto100" },
  { name: "남원관광단지·광한루원", city: "남원", category: "역사·문화", sourceLevel: "kto100" },
  { name: "완주 오성한옥마을", city: "완주", category: "역사·문화", sourceLevel: "kto100" },
  { name: "진안 마이산도립공원", city: "진안", category: "자연", sourceLevel: "kto100" },
  { name: "무주 반디랜드·태권도원", city: "무주", category: "체험", sourceLevel: "kto100" },
  { name: "순창 강천산군립공원", city: "순창", category: "자연", sourceLevel: "kto100" },
  { name: "부안 변산반도국립공원", city: "부안", category: "자연", sourceLevel: "kto100" },
  { name: "덕진공원", city: "전주", category: "강·호수", sourceLevel: "tourJeonbuk" },
  { name: "경기전", city: "전주", category: "역사·문화", sourceLevel: "tourJeonbuk" },
  { name: "전주 전동성당", city: "전주", category: "역사·문화", sourceLevel: "tourJeonbuk" },
  { name: "전주향교", city: "전주", category: "역사·문화", sourceLevel: "tourJeonbuk" },
  { name: "오목대·이목대", city: "전주", category: "역사·문화", sourceLevel: "tourJeonbuk" },
  { name: "국립전주박물관", city: "전주", category: "문화관광", sourceLevel: "tourJeonbuk" },
  { name: "한국도로공사 전주수목원", city: "전주", category: "자연", sourceLevel: "tourJeonbuk" },
  { name: "전주한옥레일바이크", city: "전주", category: "자전거 추천 코스", sourceLevel: "tourJeonbuk" },
  { name: "군산근대역사박물관", city: "군산", category: "역사·문화", sourceLevel: "tourJeonbuk" },
  { name: "군산 시간여행마을", city: "군산", category: "역사·문화", sourceLevel: "tourJeonbuk" },
  { name: "초원사진관", city: "군산", category: "도심·관광", sourceLevel: "tourJeonbuk" },
  { name: "은파호수공원", city: "군산", category: "강·호수", sourceLevel: "tourJeonbuk" },
  { name: "선유도해수욕장", city: "군산", category: "강·호수", sourceLevel: "tourJeonbuk" },
  { name: "고군산군도", city: "군산", category: "강·호수", sourceLevel: "tourJeonbuk" },
  { name: "경암동 철길마을", city: "군산", category: "도심·관광", sourceLevel: "tourJeonbuk" },
  { name: "신흥동 일본식가옥", city: "군산", category: "역사·문화", sourceLevel: "tourJeonbuk" },
  { name: "미륵사지", city: "익산", category: "역사·문화", sourceLevel: "tourJeonbuk" },
  { name: "왕궁리유적", city: "익산", category: "역사·문화", sourceLevel: "tourJeonbuk" },
  { name: "국립익산박물관", city: "익산", category: "문화관광", sourceLevel: "tourJeonbuk" },
  { name: "보석박물관", city: "익산", category: "문화관광", sourceLevel: "tourJeonbuk" },
  { name: "성당포구마을", city: "익산", category: "강·호수", sourceLevel: "tourJeonbuk" },
  { name: "나바위성당", city: "익산", category: "역사·문화", sourceLevel: "tourJeonbuk" },
  { name: "교도소세트장", city: "익산", category: "체험", sourceLevel: "tourJeonbuk" },
  { name: "달빛소리수목원", city: "익산", category: "자연", sourceLevel: "tourJeonbuk" },
  { name: "내장산 단풍생태공원", city: "정읍", category: "자연", sourceLevel: "tourJeonbuk" },
  { name: "정읍사문화공원", city: "정읍", category: "문화관광", sourceLevel: "tourJeonbuk" },
  { name: "동학농민혁명기념공원", city: "정읍", category: "역사·문화", sourceLevel: "tourJeonbuk" },
  { name: "구절초 지방정원", city: "정읍", category: "자연", sourceLevel: "tourJeonbuk" },
  { name: "피향정", city: "정읍", category: "역사·문화", sourceLevel: "tourJeonbuk" },
  { name: "무성서원", city: "정읍", category: "역사·문화", sourceLevel: "tourJeonbuk" },
  { name: "춘향테마파크", city: "남원", category: "체험", sourceLevel: "tourJeonbuk" },
  { name: "국립민속국악원", city: "남원", category: "문화관광", sourceLevel: "tourJeonbuk" },
  { name: "남원시립김병종미술관", city: "남원", category: "문화관광", sourceLevel: "tourJeonbuk" },
  { name: "지리산허브밸리", city: "남원", category: "자연", sourceLevel: "tourJeonbuk" },
  { name: "혼불문학관", city: "남원", category: "문화관광", sourceLevel: "tourJeonbuk" },
  { name: "실상사", city: "남원", category: "역사·문화", sourceLevel: "tourJeonbuk" },
  { name: "지리산둘레길 남원구간", city: "남원", category: "자전거 추천 코스", sourceLevel: "tourJeonbuk" },
  { name: "벽골제", city: "김제", category: "역사·문화", sourceLevel: "tourJeonbuk" },
  { name: "금산사", city: "김제", category: "역사·문화", sourceLevel: "tourJeonbuk" },
  { name: "아리랑문학마을", city: "김제", category: "문화관광", sourceLevel: "tourJeonbuk" },
  { name: "모악산", city: "김제", category: "자연", sourceLevel: "tourJeonbuk" },
  { name: "망해사", city: "김제", category: "역사·문화", sourceLevel: "tourJeonbuk" },
  { name: "새만금 바람길", city: "김제", category: "자전거 추천 코스", sourceLevel: "tourJeonbuk" },
  { name: "비비정", city: "완주", category: "강·호수", sourceLevel: "tourJeonbuk" },
  { name: "완주 모악산", city: "완주", category: "자연", sourceLevel: "tourJeonbuk" },
  { name: "대둔산도립공원", city: "완주", category: "자연", sourceLevel: "tourJeonbuk" },
  { name: "삼례문화예술촌", city: "완주", category: "문화관광", sourceLevel: "tourJeonbuk" },
  { name: "고산자연휴양림", city: "완주", category: "자연", sourceLevel: "tourJeonbuk" },
  { name: "안덕건강힐링체험마을", city: "완주", category: "체험", sourceLevel: "tourJeonbuk" },
  { name: "운일암반일암", city: "진안", category: "자연", sourceLevel: "tourJeonbuk" },
  { name: "진안홍삼스파", city: "진안", category: "체험", sourceLevel: "tourJeonbuk" },
  { name: "용담호", city: "진안", category: "강·호수", sourceLevel: "tourJeonbuk" },
  { name: "부귀 메타세쿼이아길", city: "진안", category: "자전거 추천 코스", sourceLevel: "tourJeonbuk" },
  { name: "데미샘자연휴양림", city: "진안", category: "자연", sourceLevel: "tourJeonbuk" },
  { name: "마이산 탑사", city: "진안", category: "역사·문화", sourceLevel: "tourJeonbuk" },
  { name: "덕유산국립공원", city: "무주", category: "자연", sourceLevel: "tourJeonbuk" },
  { name: "무주덕유산리조트", city: "무주", category: "체험", sourceLevel: "tourJeonbuk" },
  { name: "머루와인동굴", city: "무주", category: "체험", sourceLevel: "tourJeonbuk" },
  { name: "적상산사고", city: "무주", category: "역사·문화", sourceLevel: "tourJeonbuk" },
  { name: "무주구천동", city: "무주", category: "자연", sourceLevel: "tourJeonbuk" },
  { name: "라제통문", city: "무주", category: "역사·문화", sourceLevel: "tourJeonbuk" },
  { name: "장수누리파크", city: "장수", category: "체험", sourceLevel: "tourJeonbuk" },
  { name: "장수승마체험장", city: "장수", category: "체험", sourceLevel: "tourJeonbuk" },
  { name: "의암공원", city: "장수", category: "역사·문화", sourceLevel: "tourJeonbuk" },
  { name: "뜬봉샘생태공원", city: "장수", category: "자연", sourceLevel: "tourJeonbuk" },
  { name: "방화동가족휴가촌", city: "장수", category: "자연", sourceLevel: "tourJeonbuk" },
  { name: "옥정호", city: "임실", category: "강·호수", sourceLevel: "tourJeonbuk" },
  { name: "임실치즈테마파크", city: "임실", category: "체험", sourceLevel: "tourJeonbuk" },
  { name: "국사봉", city: "임실", category: "자연", sourceLevel: "tourJeonbuk" },
  { name: "사선대", city: "임실", category: "자연", sourceLevel: "tourJeonbuk" },
  { name: "붕어섬 생태공원", city: "임실", category: "강·호수", sourceLevel: "tourJeonbuk" },
  { name: "전북119안전체험관", city: "임실", category: "체험", sourceLevel: "tourJeonbuk" },
  { name: "순창 메타세콰이아길", city: "순창", category: "자전거 추천 코스", sourceLevel: "tourJeonbuk" },
  { name: "순창고추장민속마을", city: "순창", category: "체험", sourceLevel: "tourJeonbuk" },
  { name: "채계산 출렁다리", city: "순창", category: "자연", sourceLevel: "tourJeonbuk" },
  { name: "발효소스토굴", city: "순창", category: "체험", sourceLevel: "tourJeonbuk" },
  { name: "강천힐링스파", city: "순창", category: "체험", sourceLevel: "tourJeonbuk" },
  { name: "장군목유원지", city: "순창", category: "강·호수", sourceLevel: "tourJeonbuk" },
  { name: "고창선운산도립공원", city: "고창", category: "자연", sourceLevel: "tourJeonbuk" },
  { name: "고창읍성", city: "고창", category: "역사·문화", sourceLevel: "tourJeonbuk" },
  { name: "상하농원", city: "고창", category: "체험", sourceLevel: "tourJeonbuk" },
  { name: "고창 고인돌유적", city: "고창", category: "역사·문화", sourceLevel: "tourJeonbuk" },
  { name: "운곡람사르습지", city: "고창", category: "자연", sourceLevel: "tourJeonbuk" },
  { name: "학원농장", city: "고창", category: "자연", sourceLevel: "tourJeonbuk" },
  { name: "고창갯벌", city: "고창", category: "강·호수", sourceLevel: "tourJeonbuk" },
  { name: "동호해수욕장", city: "고창", category: "강·호수", sourceLevel: "tourJeonbuk" },
  { name: "채석강", city: "부안", category: "자연", sourceLevel: "tourJeonbuk" },
  { name: "변산해수욕장", city: "부안", category: "강·호수", sourceLevel: "tourJeonbuk" },
  { name: "모항해수욕장", city: "부안", category: "강·호수", sourceLevel: "tourJeonbuk" },
  { name: "내소사", city: "부안", category: "역사·문화", sourceLevel: "tourJeonbuk" },
  { name: "직소폭포", city: "부안", category: "자연", sourceLevel: "tourJeonbuk" },
  { name: "부안청자박물관", city: "부안", category: "문화관광", sourceLevel: "tourJeonbuk" },
].map((spot, index) => ({
  id: `JB-${String(index + 1).padStart(3, "0")}`,
  rank: index + 1,
  bonus: spot.sourceLevel === "kto100" ? 220 : 140 + (index % 5) * 10,
  near: 100,
  distance: Number((7.5 + (index % 15) * 1.1).toFixed(1)),
  officialSource: OFFICIAL_LANDMARK_SOURCE[spot.sourceLevel],
  ...spot,
}));

if (typeof window !== "undefined") {
  window.OFFICIAL_LANDMARKS = OFFICIAL_LANDMARKS;
  window.OFFICIAL_LANDMARK_SOURCE = OFFICIAL_LANDMARK_SOURCE;
}

if (typeof module !== "undefined") {
  module.exports = { OFFICIAL_LANDMARKS, OFFICIAL_LANDMARK_SOURCE };
}
